import { buildCodexCliArgs, CodexCliClient } from './client';
import type { CodexCommandRunnerLike, CommandExecutionResult } from './types';
class FakeRunner implements CodexCommandRunnerLike { readonly calls: readonly string[][] = []; constructor(private readonly responses: CommandExecutionResult[]) {} async execute(args: readonly string[]): Promise<CommandExecutionResult> { (this.calls as string[][]).push([...args]); const response = this.responses.shift(); if (!response) throw new Error('No fake response.'); return response; } }
const result = (stdout: string, stderr = '', exitCode = 0): CommandExecutionResult => ({ stdout, stderr, exitCode, durationMs: 1 });
describe('Codex CLI adapter', () => {
  it('builds safe plan and reasoning arguments', () => { const built = buildCodexCliArgs({ prompt: 'Plan it.', mode: 'plan', model: 'gpt-5-codex', reasoningEffort: 'high', planModeReasoningEffort: 'medium', resume: 'thread-1' }); expect(built.ok).toBe(true); if (built.ok) { expect(built.data).toEqual(expect.arrayContaining(['exec', 'resume', 'thread-1', '--model', 'gpt-5-codex', '--json', '--config', 'model_reasoning_effort="high"', '--config', 'plan_mode_reasoning_effort="medium"'])); expect(built.data.at(-1)).toContain('do not modify files'); } });
  it('rejects credential flags', () => expect(buildCodexCliArgs({ prompt: 'run', extraArgs: ['--api-key=secret'] })).toMatchObject({ ok: false, error: { category: 'validation' } }));
  it('normalizes JSONL events and returns the thread id', async () => { const runner = new FakeRunner([result([JSON.stringify({ type: 'thread.started', thread_id: 'thread-1' }), JSON.stringify({ type: 'item.completed', item: { type: 'agent_message', text: 'Plan complete.' } }), JSON.stringify({ type: 'turn.completed' })].join('\n'))]); const response = await new CodexCliClient({ runner }).plan({ prompt: 'Plan.' }); expect(response).toMatchObject({ ok: true, data: { threadId: 'thread-1', mode: 'plan' } }); });
  it('categorizes invalid models', async () => { const response = await new CodexCliClient({ runner: new FakeRunner([result('', 'Invalid model', 1)]) }).run({ prompt: 'run', model: 'missing' }); expect(response).toMatchObject({ ok: false, error: { category: 'invalid_model' } }); });
  it('reports CLI and auth health without credentials', async () => { const runner = new FakeRunner([result('codex-cli 0.144.1'), result('{"overallStatus":"fail","checks":{"auth.credentials":{"status":"fail","summary":"no Codex credentials were found"}}}', '', 1)]); const response = await new CodexCliClient({ runner }).health(); expect(response).toMatchObject({ ok: true, data: { cli: { version: '0.144.1' }, authentication: { status: 'unauthenticated' }, canRun: false } }); });
  it('reports unsupported model discovery without inventing a CLI command', async () => { const response = await new CodexCliClient({ runner: new FakeRunner([]) }).listModels(); expect(response).toMatchObject({ ok: false, error: { category: 'configuration', operation: 'models.list' } }); });
});
