import { parseFailure, success } from './errors';
import type { CodexModelSummary, CodexOutputFormat, CodexResult, CodexRunResult, CodexStreamEvent } from './types';
type JsonRecord = Record<string, unknown>;
const asRecord = (value: unknown): JsonRecord | null => typeof value === 'object' && value !== null && !Array.isArray(value) ? value as JsonRecord : null;
const asString = (value: unknown): string | null => typeof value === 'string' ? value : null;
const asNumber = (value: unknown): number | null => typeof value === 'number' && Number.isFinite(value) ? value : null;
const contentText = (value: unknown): string => { if (typeof value === 'string') return value; const item = asRecord(value); if (item && typeof item.text === 'string') return item.text; if (Array.isArray(value)) return value.map(contentText).join(''); return ''; };
export function parseCodexEvent(value: unknown): CodexStreamEvent { const item = asRecord(value); const eventType = asString(item?.type) ?? 'unknown'; const raw = value; if (eventType === 'thread.started') return { type: eventType, threadId: asString(item?.thread_id ?? item?.threadId), raw }; if (eventType === 'turn.started') return { type: eventType, raw }; if (eventType === 'turn.completed') return { type: 'completion', success: true, raw }; if (eventType === 'error' || eventType === 'turn.failed') return { type: 'completion', success: false, raw }; const nested = asRecord(item?.item); const nestedType = asString(nested?.type) ?? ''; if (nested) { if (/reasoning/i.test(nestedType)) return { type: 'reasoning', text: contentText(nested.text ?? nested.summary ?? nested.content), raw }; if (/plan|todo/i.test(nestedType)) return { type: 'plan', text: contentText(nested.text ?? nested.content), raw }; if (/message|agent_message|assistant/i.test(nestedType)) return { type: 'assistant', text: contentText(nested.text ?? nested.content ?? nested.message), raw }; if (/command|tool|mcp/i.test(nestedType)) return { type: 'tool', toolName: asString(nested.name ?? nested.tool_name), status: asString(nested.status), text: contentText(nested.output ?? nested.content), raw }; }
 if (/reasoning/i.test(eventType)) return { type: 'reasoning', text: contentText(item?.text ?? item?.summary ?? item?.content), raw }; if (/plan|todo/i.test(eventType)) return { type: 'plan', text: contentText(item?.text ?? item?.content), raw }; if (/command|tool|mcp/i.test(eventType)) return { type: 'tool', toolName: asString(item?.name ?? item?.tool_name), status: asString(item?.status), text: contentText(item?.output ?? item?.content), raw }; if (/usage/i.test(eventType)) { const usage = asRecord(item?.usage) ?? item ?? {}; return { type: 'usage', inputTokens: asNumber(usage.input_tokens ?? usage.inputTokens), outputTokens: asNumber(usage.output_tokens ?? usage.outputTokens), raw }; } if (/message|assistant/i.test(eventType)) return { type: 'assistant', text: contentText(item?.text ?? item?.content ?? item?.message), raw }; if (eventType === 'result' || eventType === 'turn.result') return { type: 'result', text: contentText(item?.result ?? item?.text ?? item?.content), threadId: asString(item?.thread_id ?? item?.threadId), raw }; return { type: 'unknown', eventType, raw }; }
export function parseCodexOutput(stdout: string, outputFormat: CodexOutputFormat, mode: 'plan' | 'execute', operation = 'run'): CodexResult<CodexRunResult> { if (outputFormat === 'text') return success({ text: stdout.trim(), threadId: null, model: null, mode, outputFormat, events: [], raw: stdout }); const events: CodexStreamEvent[] = []; for (const line of stdout.split(/\r?\n/).filter(Boolean)) { try { events.push(parseCodexEvent(JSON.parse(line) as unknown)); } catch { return parseFailure(operation, 'The Codex CLI returned invalid JSONL output.'); } } if (events.length === 0) return parseFailure(operation, 'The Codex CLI returned an empty JSONL response.'); const result = [...events].reverse().find((event) => event.type === 'result'); const thread = events.find((event) => event.type === 'thread.started'); const text = result?.type === 'result' ? result.text : events.filter((event) => event.type === 'assistant' || event.type === 'plan' || event.type === 'reasoning').map((event) => event.text).join(''); return success({ text, threadId: result?.type === 'result' ? result.threadId : thread?.type === 'thread.started' ? thread.threadId : null, model: null, mode, outputFormat, events, raw: events.map((event) => event.raw) }); }
export function parseCodexVersion(stdout: string): CodexResult<string> { const match = /codex-cli\s+v?([0-9][^\s]*)/i.exec(stdout) ?? /\b\d+(?:\.\d+)+\b/.exec(stdout); return match ? success(match[1]) : parseFailure('health.cli_version', 'The Codex CLI version output was not recognized.'); }
export function parseCodexModels(stdout: string, operation = 'models.list'): CodexResult<readonly CodexModelSummary[]> { try { const value = JSON.parse(stdout) as unknown; const values = Array.isArray(value) ? value : asRecord(value)?.models; if (Array.isArray(values)) return success(values.flatMap((entry) => { const item = asRecord(entry); const id = asString(item?.id ?? item?.model ?? entry); return id ? [{ id, name: asString(item?.name ?? item?.display_name), raw: entry }] : []; })); } catch { /* accept line-oriented output below */ } const lines = stdout.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); return lines.length ? success(lines.map((id) => ({ id, name: null, raw: id }))) : parseFailure(operation, 'The Codex CLI returned no model entries.'); }
